// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shift_dashboard.Data;

namespace shift_dashboard.Migrations
{
    [DbContext(typeof(DashboardContext))]
    [Migration("20210120005612_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("shift_dashboard.Model.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Balance")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Address" }, "Index_Address")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("shift_dashboard.Model.Delegate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<double>("Approval")
                        .HasColumnType("float");

                    b.Property<int>("Missedblocks")
                        .HasColumnType("int");

                    b.Property<int>("Producedblocks")
                        .HasColumnType("int");

                    b.Property<double>("Productivity")
                        .HasColumnType("float");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Vote")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex(new[] { "Address" }, "Index_Address")
                        .IsUnique()
                        .HasDatabaseName("Index_Address1");

                    b.ToTable("Delegates");
                });

            modelBuilder.Entity("shift_dashboard.Model.DelegateStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DelegateId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("TotalVoters")
                        .HasColumnType("int");

                    b.Property<long>("TotalVotes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DelegateId");

                    b.ToTable("DelegateStats");
                });

            modelBuilder.Entity("shift_dashboard.Model.Delegate", b =>
                {
                    b.HasOne("shift_dashboard.Model.Account", null)
                        .WithMany("DelegatesVote")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("shift_dashboard.Model.DelegateStat", b =>
                {
                    b.HasOne("shift_dashboard.Model.Delegate", null)
                        .WithMany("DelegateStats")
                        .HasForeignKey("DelegateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("shift_dashboard.Model.Account", b =>
                {
                    b.Navigation("DelegatesVote");
                });

            modelBuilder.Entity("shift_dashboard.Model.Delegate", b =>
                {
                    b.Navigation("DelegateStats");
                });
#pragma warning restore 612, 618
        }
    }
}
